AWSTemplateFormatVersion: '2010-09-09'
Description: GBaaS Infrastructure

# This is just a workaround
Parameters:
  BackupEntities:
    Description: Semicolon seperated list of entities to backup
    Type: String
    Default: ""
  BackupFunctionBucket:
    Description: Name of the bucket where the backup function is found
    Type: String
    Default: "DEFAULT_BUCKET"
  BackupFunctionBucketKey:
    Description: Name of the zipped function inside the bucket
    Type: String
    Default: "backupfn.zip"
  UseDefBucket:
    Description: Set this to false if you want to use a custom BackupFunctionBucket
    Type: String
    AllowedValues:
      - "true"
      - "false"
    Default: "true"

Conditions:
  UseDefaultBackupFunctionBucket: !Equals [ !Ref UseDefBucket, "true" ]

Resources:
  # Core bucket, containing current backups and the internal data (like the frontend code)
  CoreBucket:
    Type: 'AWS::S3::Bucket'
    # DeletionPolicy: Retain // Add to not delete the bucket when deleting the stack
    Properties:
      BucketName: !Sub 'corebucket-gbaas-prod-${AWS::Region}-1'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 3
      ReplicationConfiguration:
        Role: !GetAtt
          - DeepArchiveReplicationRole
          - Arn
        Rules:
          - Destination:
              Bucket: !Sub 'arn:aws:s3:::${DeepArchiveBucket}'
              StorageClass: DEEP_ARCHIVE
            Filter:
              # This is the path where the repositorys are stored
              Prefix: "repos/"
            Priority: 1
            Status: Enabled
            DeleteMarkerReplication:
              Status: Disabled
  CoreBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref CoreBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${CoreBucket}/web/*'
              - !Sub 'arn:aws:s3:::${CoreBucket}/repos/*'
            Principal: '*'
            
  # Deep Archive bucket, where backups are replicated to
  DeepArchiveBucket:
    Type: 'AWS::S3::Bucket'
    # DeletionPolicy: Retain // Add to not delete the bucket when deleting the stack
    Properties:
      BucketName: !Sub 'dabucket-gbaas-prod-${AWS::Region}-1'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 21
              NewerNoncurrentVersions: 2
  # Role to replicate to DeepArchiveBucket
  DeepArchiveReplicationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
  DeepArchiveReplicationPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetReplicationConfiguration'
              - 's3:ListBucket'
              - 's3:GetObjectVersion'
              - 's3:GetObjectVersionAcl'
              - 's3:ReplicateObject'
              - 's3:ReplicateDelete'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${DeepArchiveBucket}/*'
            
      PolicyName: DeepArchiveReplicationPolicy
      Roles:
        - !Ref DeepArchiveReplicationRole

  # Core Backup Function (Code is added through the aws cli in CI/CD)
  BackupFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub 'backupfn-gbaas-prod-${AWS::Region}-1'
      Timeout: 900 # 15 Minutes
      EphemeralStorage:
        Size: 512
      MemorySize: 512
      Runtime: 'go1.x'
      Role: !GetAtt
        - BackupFunctionRole
        - Arn
      Handler: 'main'
      Environment:
        Variables:
          GBAAS_COREBUCKET_NAME: !Ref CoreBucket
          GBAAS_COREBUCKET_REGION: !Sub ${AWS::Region}
          GBAAS_ENTITIES: !Ref BackupEntities
      Code:
        S3Bucket: !If [UseDefaultBackupFunctionBucket, !Ref CoreBucket, !Ref BackupFunctionBucket]
        S3Key: !Ref BackupFunctionBucketKey
  # Role to allow access to CoreBucket
  BackupFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Policies:
        - PolicyName: 'LambdaAccessToRegularS3Bucket'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ['s3:GetObject', 's3:PutObject']
                Resource: !Sub 'arn:aws:s3:::${CoreBucket}/*'
   # EventBridge rule to schedule the backup job
  EventRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: !Sub "Triggers backup job for ${BackupFunction}"
      ScheduleExpression: 'rate(1 day)'
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt
            - BackupFunction
            - Arn
          Id: !Ref BackupFunction
            
  EventRulePermission: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !GetAtt
        - BackupFunction
        - Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt
        - EventRule
        - Arn

Outputs:
  # Those values can be parsed by CI/CD pipe to upload the webapp / lambda code
  CoreBucketName:
    Value: !Ref CoreBucket
  BackupFunctionArn:
    Value: !Ref BackupFunction
